# Generated by Django 3.0.1 on 2020-02-07 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.TextField()),
                ('match_email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_email', models.TextField()),
                ('user_address', models.TextField()),
                ('user_gender', models.TextField()),
                ('user_age', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('yourpost', models.TextField()),
                ('posteddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('statuses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matchmaking.User')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matchmaking.User')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.TextField()),
                ('reciever_name', models.TextField()),
                ('message', models.TextField()),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matchmaking.Match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='matches',
            field=models.ManyToManyField(to='Matchmaking.User'),
        ),
    ]
