# Generated by Django 3.0.1 on 2020-02-06 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('yourpost', models.TextField()),
                ('posteddate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
