# Generated by Django 3.0.1 on 2020-02-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matchmaking', '0002_auto_20200207_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='statuses',
        ),
    ]
